name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - run: chmod +x gradlew
      - run: ./gradlew --version --no-daemon
      - run: ./gradlew build shadowJar --stacktrace --no-daemon --console=plain --warning-mode all
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: build/libs/*.jar